FROM arm32v7/node:latest
LABEL maintainer="dragonchaser <matrixtitlebot@datenschmutz.space>"
COPY qemu-arm-static /usr/bin
RUN git clone https://github.com/dragonchaser/matrixTitleBot /matrixTitleBot
WORKDIR /matrixTitleBot
RUN npm install
CMD node titlebot.js
